import type { Volume, ChapterSummary, Chapter, Character, TimelineEntry } from './types';

export type { Volume, ChapterSummary, Chapter, Character, TimelineEntry };

// ---------------------------------------------------------------------------
// Data arrays — start empty, populated in-place by `ready()`.
// ---------------------------------------------------------------------------

/** All archive volumes (call `await ready()` first). */
export const volumes: Volume[] = [];

/** All characters (call `await ready()` first). */
export const characters: Character[] = [];

/** Timeline entries (call `await ready()` first). */
export const timeline: TimelineEntry[] = [];

// ---------------------------------------------------------------------------
// Data loading — lazy-loads the generated JSON files so the module works even
// before the build script has created them in src/lib/archive/data/.
//
// The exported arrays are mutated *in-place* by `ready()`, so any reference
// captured before the call will automatically see the populated data once the
// Promise resolves.
// ---------------------------------------------------------------------------

async function loadData(): Promise<{
  volumes: Volume[];
  characters: Character[];
  timeline: TimelineEntry[];
}> {
  let volumes: Volume[] = [];
  let characters: Character[] = [];
  let timeline: TimelineEntry[] = [];

  try {
    volumes = (await import('./data/catalog.json')).default as unknown as Volume[];
  } catch {
    // catalog.json not yet generated by the build script
  }

  try {
    characters = (await import('./data/characters.json')).default as unknown as Character[];
  } catch {
    // characters.json not yet generated by the build script
  }

  try {
    timeline = (await import('./data/timeline.json')).default as unknown as TimelineEntry[];
  } catch {
    // timeline.json not yet generated by the build script
  }

  return { volumes, characters, timeline };
}

let _promise: Promise<void> | null = null;

/**
 * Ensure the archive data has been loaded.  Call this (and `await` it) before
 * reading `volumes`, `characters`, or `timeline` — for example inside a
 * server component or route handler:
 *
 * ```ts
 * import { ready, volumes } from '@/lib/archive/catalog';
 * await ready();
 * // now `volumes` is populated
 * ```
 */
export async function ready(): Promise<void> {
  if (!_promise) {
    _promise = loadData().then(({ volumes: v, characters: c, timeline: t }) => {
      // Mutate in-place so the exported references stay valid.
      volumes.push(...v);
      characters.push(...c);
      timeline.push(...t);
    });
  }
  return _promise;
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export function getVolume(slug: string): Volume | undefined {
  return volumes.find((v) => v.slug === slug);
}

export function getChapter(slug: string): ChapterSummary | undefined {
  for (const vol of volumes) {
    const ch = vol.chapters.find((c) => c.slug === slug);
    if (ch) return ch;
  }
  return undefined;
}

export function getCharacter(id: string): Character | undefined {
  return characters.find((c) => c.id === id);
}

export function getCharactersBySchool(school: string): Character[] {
  return characters.filter((c) => c.school?.includes(school));
}

export function searchChapters(query: string): ChapterSummary[] {
  const q = query.toLowerCase();
  const results: ChapterSummary[] = [];
  for (const vol of volumes) {
    for (const ch of vol.chapters) {
      if (
        ch.title.toLowerCase().includes(q) ||
        ch.epigraph?.toLowerCase().includes(q)
      ) {
        results.push(ch);
      }
    }
  }
  return results;
}
